apiVersion: v1
entries:
  irc:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-12-01T09:38:25.762958Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: f2836c433303809148869cfa1bb24f2d7c188a056bf6b5c31554a772bfc54e4d
    home: irc.zaakonline.nl
    icon: irc.zaakonline.nl
    name: irc
    urls:
    - irc-0.1.0.tgz
    version: 0.1.0
generated: "2020-12-01T09:38:25.7468885Z"
